language: objective-c

script:
  xcodebuild 
    -workspace xkcd.xcworkspace 
    -scheme xkcdTests 
    -sdk iphonesimulator
    -arch i386
    build test
    ONLY_ACTIVE_ARCH=NO
    CODE_SIGN_IDENTITY="" 
    CODE_SIGNING_REQUIRED=NO
