language: objective-c
osx_image: xcode7.3

script:
  xcodebuild 
    -workspace xkcd.xcworkspace 
    -scheme xkcdTests 
    -sdk iphonesimulator
    build test
    ONLY_ACTIVE_ARCH=NO
    CODE_SIGN_IDENTITY="" 
    CODE_SIGNING_REQUIRED=NO
