language: objective-c

script:
  xcodebuild 
    -workspace xkcd.xcworkspace 
    -scheme xkcdTests 
    -sdk iphonesimulator
    -destination 'platform=iOS Simulator,name=iPhone 6 Plus'
    build test
    CODE_SIGN_IDENTITY="" 
    CODE_SIGNING_REQUIRED=NO
