language: objective-c
osx_image: xcode8.3

script:
  xcodebuild 
    -workspace xkcd.xcworkspace 
    -scheme xkcdTests 
    -sdk iphonesimulator
    -destination 'platform=iOS Simulator,name=iPhone 7'
    build test
    ONLY_ACTIVE_ARCH=NO
    CODE_SIGN_IDENTITY="" 
    CODE_SIGNING_REQUIRED=NO
