language: objective-c
osx_image: xcode9.2

before_install: rvm use $RVM_RUBY_VERSION
install: bundle install --without=documentation
after_success: slather

script:
  xcodebuild 
    -workspace xkcd.xcworkspace 
    -scheme xkcdTests 
    -sdk iphonesimulator
    -destination 'platform=iOS Simulator,name=iPhone 8'
    build test
    ONLY_ACTIVE_ARCH=YES
    VALID_ARCHS=x86_64
    CODE_SIGN_IDENTITY="" 
    CODE_SIGNING_REQUIRED=NO
